"""Loopback-only TCP forwarding to the existing vehicle console.

This is not a second controller: it forwards bytes unchanged, including the
existing origin checks, control tokens, streams and browser lease requests.
No proxy environment is used and no drive request is generated by this tool.
"""
import argparse
import select
import socket
import socketserver


class ConsoleForward(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


class Connection(socketserver.BaseRequestHandler):
    def handle(self):
        try:
            upstream = socket.create_connection(self.server.vehicle_address, timeout=5)
        except OSError:
            body = ('<!doctype html><meta charset="utf-8"><title>车辆连接未就绪</title>'
                    '<h1>本机入口已启动，车端暂未连通</h1>'
                    '<p>请检查车辆供电、Tailscale 和车端控制服务。恢复连接后刷新此页。</p>'
                    '<p>没有发送车辆控制指令。</p><button onclick="location.reload()">重新连接</button>').encode('utf-8')
            try:
                # Consume the request headers before returning a useful error,
                # otherwise unread data can make Windows reset the TCP socket.
                self.request.settimeout(1)
                header = b''
                while b'\r\n\r\n' not in header and len(header) < 16384:
                    part = self.request.recv(4096)
                    if not part:
                        return
                    header += part
                self.request.sendall(b'HTTP/1.1 503 Service Unavailable\r\n'
                                     b'Content-Type: text/html; charset=utf-8\r\n'
                                     b'Cache-Control: no-store\r\nConnection: close\r\n'
                                     + f'Content-Length: {len(body)}\r\n\r\n'.encode() + body)
            except OSError:
                pass
            return
        try:
            with upstream:
                peers = (self.request, upstream)
                for peer in peers:
                    peer.settimeout(2)
                    peer.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
                while True:
                    readable, _, _ = select.select(peers, [], [], 1)
                    for source in readable:
                        data = source.recv(65536)
                        if not data:
                            return
                        target = upstream if source is self.request else self.request
                        target.sendall(data)
        except (OSError, TimeoutError):
            # Closing both ends preserves the original console's loss-of-client
            # handling. Never retry or replay a request that may control motion.
            return


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--port', type=int, default=8082)
    parser.add_argument('--vehicle-host', default='100.124.156.117')
    parser.add_argument('--vehicle-port', type=int, default=8080)
    args = parser.parse_args()
    with ConsoleForward(('127.0.0.1', args.port), Connection) as server:
        server.vehicle_address = (args.vehicle_host, args.vehicle_port)
        print(f'Console: http://127.0.0.1:{args.port}/ -> '
              f'{args.vehicle_host}:{args.vehicle_port}; no drive commands generated', flush=True)
        try:
            server.serve_forever(poll_interval=0.25)
        except KeyboardInterrupt:
            pass


if __name__ == '__main__':
    main()
